# Generated by Django 5.2.4 on 2025-07-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_block_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
